name: Deploy

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        node-version: 12
      env:
        AWS_EC2_METADATA_DISABLED: true
    - run: npm install -g yarn
    - run: yarn install --frozen-lockfile
    - run: yarn run build
    - run: aws s3 sync ./out s3://[site-l2code]
