name: Deploy

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          node-version: 12
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run build
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          AWS_DEFAULT_REGION: 'us-west-2'
      - run: aws s3 sync ./out s3://site-l2code
