name: Deploy

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./site-l2
    steps:
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        node-version: 12
    - run: npm install -g yarn
    - run: yarn install --frozen-lockfile
    - run:
        cd ../
        yarn run build
    - run: aws s3 sync ./out s3://[site-l2code]
